name: Build and Publish Package

on:
  push:
    tags:
      - "v*-python"

jobs:
  build-package:
    name: Build Python package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest setuptools jsonschema pytest-cov twine build
    - name: Install python package
      run: |
        pip install implementations/python/
    - name: Test with pytest
      run: |
        pytest -r a implementations/python/tests/
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      working-directory: implementations/python
      run: |
        python -m build -s -w
        twine upload dist/*